chore[custom-init]: update formatting on prints

diff --git a/root/etc/s6-overlay/s6-rc.d/init-custom-files/run b/root/etc/s6-overlay/s6-rc.d/init-custom-files/run
--- a/root/etc/s6-overlay/s6-rc.d/init-custom-files/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-custom-files/run
@@ -6,17 +6,18 @@ SCRIPTS_DIR="/custom-cont-init.d"
 
 # Make sure custom init directory exists and has files in it
 if [[ -e "${SCRIPTS_DIR}" ]] && [[ -n "$(/bin/ls -A ${SCRIPTS_DIR} 2>/dev/null)" ]]; then
-    echo "[custom-init] Files found, executing"
+    echo -e " CustomInit   : Files found, executing"
     for SCRIPT in "${SCRIPTS_DIR}"/*; do
         NAME="$(basename "${SCRIPT}")"
         if [[ -f "${SCRIPT}" ]]; then
-            echo "[custom-init] ${NAME}: executing..."
+            echo -e " CustomInit   : Running ${NAME} - ${SCRIPT}"
             /bin/bash "${SCRIPT}"
-            echo "[custom-init] ${NAME}: exited $?"
+
+            echo -e " CustomInit   : Exited ${NAME} - $?"
         elif [[ ! -f "${SCRIPT}" ]]; then
-            echo "[custom-init] ${NAME}: is not a file"
+            echo -e " CustomInit   : Error - ${NAME} is not a file"
         fi
     done
 else
-    echo "[custom-init] No custom files found, skipping..."
+    echo -e " CustomInit   : No custom files found, skipping"
 fi
